### ISSUE TITLE
Add an option for working path

### ISSUE THREAD

**Issue by mzyil** [trilogy-group/action-npm-install-dependencies#5]
In the Tempo repository we do multiple builds in 1 run, since this package does not accept a sub-directory as an option we are not able to cache the npm packages.

I tried to switch between folders using the `cd` linux command but it did not work: https://github.com/trilogy-group/pulse-alp/actions/runs/3387951394/jobs/5629341784 (you may need access to see it)

![image](https://user-images.githubusercontent.com/6615389/199796904-f16660e5-fcb7-489e-8a4f-f65d63985074.png)

**Comment by Tantalon** [comment]
Since it's the same codebase, why wouldn't you use the same folder and just switch branches, rather than checking out everything again?

I'm happy to take a pull request to add subfolder support, but you'd have to use separate cache keys for each (because there's no guarantee that the two folders are the same project), which will be less efficient than using the same folder and same cache.

**Comment by Tantalon** [comment]
v2 now contains support for specific folders with the `target` option
